// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sandwich_King_DB.Data.EndToEnd
{
    public partial class Image
    {
        public string ImageId { get; set; }
        public string UserName { get; set; }
        public string ImageFilepath { get; set; }
        public DateTime? Date { get; set; }
        public string Tags { get; set; }
    }
}