// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sandwich_King_DB.Data.EndToEnd
{
    public partial class ImageTags
    {
        public string TagId { get; set; }
        public string TagName { get; set; }
    }
}